apiVersion: v1
kind: Service
metadata:
  name: uipod
spec:
  selector:
    app: uipod
  ports:
    - port: 8001
      targetPort: 8001
  type: LoadBalancer
  loadBalancerIP: 35.224.3.25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uipod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uipod
  template:
    metadata:
      labels:
        app: uipod
    spec:
      containers:
        - name: uipod
          image: mestryshweta30/uipod:1.0.0
          ports:
            - containerPort: 8001
          resources: 
            limits: 
              cpu: 100m
            requests:
              cpu: 100m
          env:
            - name: QUESTIONAIREPOD_URL
              value: http://35.224.3.25:8002
            - name: FACEBOX_URL
              value: http://35.224.3.25:8080 
          imagePullPolicy: Always